apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - install.yaml

# Common labels for all ArgoCD resources
commonLabels:
  app.kubernetes.io/part-of: konecta-erp
